apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  labels:
    app: app2
spec:
  replicas: {{ .Values.app2.replicaCount }}
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2-container
        image: {{ .Values.app2.image }}
        ports:
        - containerPort: {{ .Values.app2.servicePort }}
        
        # --- ДОБАВЛЯЕМ ПРОВЕРКИ ЗДОРОВЬЯ ---
        livenessProbe:
          tcpSocket:
            port: 80 # Проверка, что порт 80 открыт
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5

        readinessProbe:
          tcpSocket:
            port: 80 # Проверка, что порт 80 открыт
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        # --------------------------------
