# devops-mini-project-chart/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "devops-mini-project-chart.fullname" . }}-ingress
  labels:
    {{- include "devops-mini-project-chart.labels" . | nindent 4 }}
  annotations:
    # Используйте эти аннотации для Ingress Controller Nginx
    nginx.ingress.kubernetes.io/rewrite-target: /1$
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      # Правило 1: App1. Путь теперь заканчивается на (.*)
      - path: /app1/(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "devops-mini-project-chart.fullname" . }}-app1
            port:
              number: 80
      # Правило 2: App2. Путь теперь заканчивается на (.*)
      - path: /app2/(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "devops-mini-project-chart.fullname" . }}-app2
            port:
              number: 80
      # Правило 3: App3 Путь теперь заканчивается на (.*)
      - path: /app3/(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "devops-mini-project-chart.fullname" . }}-app3
            port:
              number: 80
      # Правило 4: Весь остальной трафик идет на Nginx Load Balancer
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "devops-mini-project-chart.fullname" . }}-nginx
            port:
              number: 80
