# devops-mini-project-chart/templates/ingress.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "devops-mini-project-chart.fullname" . }}-ingress
  labels:
    {{- include "devops-mini-project-chart.labels" . | nindent 4 }}
  annotations:
    # Используем REGEX для обработки пути
    nginx.ingress.kubernetes.io/use-regex: "true"
    # ИСПРАВЛЕНИЕ: Используем стандартную аннотацию для вырезания префикса
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # Указываем класс Ingress (для Minikube)
    kubernetes.io/ingress.class: "nginx" 
spec:
  rules:
  - http:
      paths:
      # Правило 1: App1. Используем RegEx в Path: /app1/(.*)
      - path: /app1/(.*)
        pathType: Prefix # <-- Вернули Prefix
        backend:
          service:
            name: {{ include "devops-mini-project-chart.fullname" . }}-app1
            port:
              number: 80
      # Правило 2: App2
      - path: /app2/(.*)
        pathType: Prefix # <-- Вернули Prefix
        backend:
          service:
            name: {{ include "devops-mini-project-chart.fullname" . }}-app2
            port:
              number: 80
      # Правило 3: App3
      - path: /app3/(.*)
        pathType: Prefix # <-- Вернули Prefix
        backend:
          service:
            name: {{ include "devops-mini-project-chart.fullname" . }}-app3
            port:
              number: 80
      # Правило 4: Nginx (Root Path)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "devops-mini-project-chart.fullname" . }}-nginx
            port:
              number: 80
