name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build app1
      - name: Build app1
        uses: docker/build-push-action@v5
        with:
          context: ./app1
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-mini-project-app1:latest

      # Build app2
      - name: Build app2
        uses: docker/build-push-action@v5
        with:
          context: ./app2
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-mini-project-app2:latest

      # Build app3
      - name: Build app3
        uses: docker/build-push-action@v5
        with:
          context: ./app3
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-mini-project-app3:latest

      # Build proxy (nginx)
      - name: Build proxy
        uses: docker/build-push-action@v5
        with:
          context: ./proxy
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-mini-project-proxy:latest

